package ch.epfl.sdp.SocialTests;


import androidx.test.espresso.ViewInteraction;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.filters.LargeTest;
import androidx.test.rule.ActivityTestRule;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import ch.epfl.sdp.ui.game.MainMenuActivity;
import ch.epfl.sdp.R;

import static androidx.test.espresso.Espresso.onView;
import static androidx.test.espresso.action.ViewActions.click;
import static androidx.test.espresso.assertion.ViewAssertions.matches;
import static androidx.test.espresso.matcher.ViewMatchers.isDisplayed;
import static androidx.test.espresso.matcher.ViewMatchers.withId;

@LargeTest
@RunWith(AndroidJUnit4.class)
public class FriendsListActivityTest {

    @Rule
    public ActivityTestRule<MainMenuActivity> mActivityTestRule = new ActivityTestRule<>(MainMenuActivity.class);

    public void step1() {
        //************************************ Click on "Friends" to go the social/chat feature *******************************//
        ViewInteraction appCompatButton2 = onView(withId(R.id.friendsButton));
        appCompatButton2.perform(click());
    }

    public void step2() {
        //********************************* Check that "Add Friends" (to search for users) is displayed ************************//
        ViewInteraction button = onView(withId(R.id.button_add_friends));
        button.check(matches(isDisplayed()));
    }

    public void step3() {

        // ******************************* Check that the scroll view showing list of friends is displayed ********************//
        ViewInteraction scrollView = onView(withId(R.id.nestedScrollView));
        scrollView.check(matches(isDisplayed()));
    }

    // auto-generated by test recorder
    @Test
    public void friendsListActivityTest() {
        step1();
        step2();
        step3();
    }

}
